[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "IIRD"
version = "0.0.1"
authors = [
  { name="Kishore Kumar Tarafdar", email="kkt.compute@gmail.com" },
]
description = "Fast trainable D-dimensional IIR filter layers in TensorFlow"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
  "tensorflow>=2.15",
  "numpy",
  "scipy",
  "matplotlib",
]
classifiers = [
  "Programming Language :: Python :: 3",
  "Operating System :: OS Independent",
  "Topic :: Scientific/Engineering",
  "Intended Audience :: Science/Research"
]
license = "Apache-2.0"
license-files = [ "LICENSE" ]

[project.urls]
Homepage = "https://github.com/kkt-ee/IIRD"
Issues = "https://github.com/kkt-ee/IIRD/issues"

[tool.hatch.build.targets.wheel]
packages = ["IIRD"]
